server:
  port: 8009

spring:
  application:
    name: service-acl

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#整合mybatis
mybatis:
  type-aliases-package: com.zyu.aclservice.entity
  mapper-locations: classpath:com/zyu/aclservice/mapper/*.xml







#spring.redis.host=192.168.44.132
#spring.redis.port=6379
#spring.redis.database= 0
#spring.redis.timeout=1800000

